version: '3.8'

services:
  bot:
    image: krivse/ctbot:v1.1.14.07.24
#    build:
#      context: .
    env_file:
      - .env
    volumes:
      - ./logs_data:/app/logs/logs
    command: python3 -m bot
    restart: always
